spring:
  application:
    name: swetlox
  mail:
    host: smtp.gmail.com
    port: 465
    username: ************@gmail.com
    password: ***********
    properties:
      mail:
        smtp:
          auth: true              # Enable SMTP authentication
          starttls:
            enable: true         # Enable TLS
          ssl:
            trust: "*"        # Enable SSL (set to true if using SSL)
      default:
        encoding: UTF-8     # Email encoding
  data:
    mongodb:
      port: 27017
      host: localhost
      database: dbswetlox
  servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB
server:
  port: 9000
  servlet:
    context-path: "/swetlox"
jwt:
  secret: "w7sF7KhZj9UQj5lZ+3O7JH8c4u/D8AeO4jW9F9K4HJk="
  expiry-time: 100000000
  issuer: "swetlox"
